#!/bin/sh

# Copyright (c) Nate Wiger http://nateware.com
# allmod - just return all .pm files for other scripts

if [ $# -gt 1 ]; then
    cat <<EOF >&2
Usage: $0
EOF
    exit 2
fi

cd `dirname $0`/..
find lib -name '*.pm' -type f "$@"

