#!/bin/sh

# Copyright (c) Nate Wiger http://nateware.com
# mkpkg - trivial packager for CGI::FormBuilder
cd `dirname $0`/..
[ $DEBUG ] && set -x
pwd=$PWD

mod=CGI::FormBuilder
pkg=CGI-FormBuilder
pod=pod
inc="Makefile.PL lib pod t"
doc="README Changes MANIFEST INSTALL"

ver=${1:-`/usr/bin/perl -I"$PWD/lib" -M$mod -e 'print $'$mod::VERSION`} || exit $?
echo "This will build a CPAN pkg for $mod v$ver"
echo "Continue (y/n) [y]? \c"
read ans
[ ${ans:-y} = y ] || exit 99

# Create a temp dir that we can tgz into CPAN pkg name
tmpdir=`mktemp -d /tmp/mkpkg.XXXXXX`
tmppkg=$tmpdir/$pkg-$ver
mkdir -p $tmppkg || exit 2

# use h to expand symlinks, since Perl won't install them 
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true  # fucking Mac
export COPYFILE_DISABLE=true
cp -rp $inc $tmppkg
cd $tmppkg || exit 3

# create doc files from pods
pod2text $pod/README.pod >README
pod2text $pod/INSTALL.pod >INSTALL
pod2text $pod/Changes.pod >Changes

# Generate MANIFEST
touch MANIFEST  # need MANIFEST in MANIFEST
find $inc $doc Makefile.PL -type f -print | sort >MANIFEST

cd ..
tar cvhf $pkg-$ver.tar $pkg-$ver || exit 4
gzip $pkg-$ver.tar || exit 5
mv $pkg-$ver.tar.gz $pkg-$ver.tgz || exit 6
[ -d $pwd/pkgs ] || mkdir -p $pwd/pkgs
mv $pkg-$ver.tgz $pwd/pkgs
cd /
rm -rf $tmpdir

echo "Packaging complete!"
echo "Don't forget:"
echo "    git add $pwd/pkgs/$pkg-$ver.tgz"

